# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabeties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preg', models.CharField(max_length=25)),
                ('plas', models.CharField(max_length=25)),
                ('pres', models.CharField(max_length=25)),
                ('skin', models.CharField(max_length=25)),
                ('test', models.CharField(max_length=25)),
                ('mass', models.CharField(max_length=25)),
                ('pedi', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=25)),
                ('class_data', models.CharField(max_length=25)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
