# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MlDiabetiesModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabeties',
            name='age',
            field=models.CharField(max_length=25, verbose_name='Age (years) '),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='class_data',
            field=models.CharField(max_length=25, verbose_name='Diabetes result'),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='mass',
            field=models.CharField(max_length=25, verbose_name='Body mass index (weight in kg/(height in m)^2) '),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='pedi',
            field=models.CharField(max_length=25, verbose_name='Diabetes pedigree function '),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='plas',
            field=models.CharField(max_length=25, verbose_name='Plasma glucose concentration a 2 hours in an oral glucose tolerance test'),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='preg',
            field=models.CharField(max_length=25, verbose_name='Number of times pregnant'),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='pres',
            field=models.CharField(max_length=25, verbose_name='Diastolic blood pressure (mm Hg)'),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='result',
            field=models.CharField(max_length=10, verbose_name='Diabetes result1'),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='skin',
            field=models.CharField(max_length=25, verbose_name='Triceps skin fold thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='diabeties',
            name='test',
            field=models.CharField(max_length=25, verbose_name='2-Hour serum insulin (mu U/ml)'),
        ),
    ]
